config/routes.rb
Freader::Application.routes.draw do

  resources :feeds

  post 'sessions', :to => 'sessions#create'
  delete 'sessions', :to => 'sessions#destroy'
  resources :articles, :only => [:index, :update]
  get 'feeds/:user_feed_id/articles', :to => 'articles#index'
  root :to => 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :author, :url, :content, :feed, :published_at, :summary, :title

  belongs_to :user_feed_article
  belongs_to :feed
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  attr_accessible :etag, :feed_url, :last_modified, :name, :url

  has_many :user_feeds, :dependent => :destroy
  has_many :articles, :dependent => :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :create_remember_token
  attr_accessible :email, :remember_token

  has_many :user_feeds, :dependent => :destroy
  has_many :feeds, :through => :user_feeds
  has_many :user_feed_articles, :through => :user_feeds

  def create_feed(url)
    remote_feed = Feedzirra::Feed.fetch_and_parse(url)
    local_feed = Feed.create(name: remote_feed.title, url: remote_feed.url, feed_url: remote_feed.feed_url, etag: remote_feed.etag, last_modified: remote_feed.last_modified)
    user_feed = self.user_feeds.create(feed: local_feed)
    remote_feed.sanitize_entries!
    remote_feed.entries[0..9].each do |entry|
      article = local_feed.articles.create(title: entry.title,
                             author: entry.author,
                             url: entry.url,
                             summary: entry.summary,
                             content: entry.content,
                             published_at: entry.published)
      user_feed.user_feed_articles.create(article: article, read: false, keep_unread: false)
    end
    user_feed
  end

  def articles(params)
    articles_rel = user_feed_articles
    articles_rel = articles_rel.joins(:article)
    if params[:user_feed_id].present?
      articles_rel = articles_rel.where(:user_feed_id => params[:user_feed_id])
    end
    if params[:unread]
      articles_rel = articles_rel.where('read is false or keep_unread is true')
    end

    articles_rel.order('articles.published_at desc')
  end

  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/models/user_feed.rb
class UserFeed < ActiveRecord::Base
  attr_accessible :feed, :user

  belongs_to :user
  belongs_to :feed
  has_many :user_feed_articles
  has_many :articles, :through => :user_feed_articles

  def unread_articles
    self.user_feed_articles.where("read = false or keep_unread = true")
  end

  def as_json(options={})
    super(options).merge({
      :unread_articles_count => self.unread_articles.count,
      :url => self.feed.url,
      :name => self.feed.name
    })
  end
end

app/models/user_feed_article.rb
class UserFeedArticle < ActiveRecord::Base
  attr_accessible :article, :keep_unread, :read, :user_feed, :favorite

  belongs_to :user_feed
  belongs_to :article

  def as_json(options={})
    ret = super(options).merge(self.article.as_json())
    ret[:id] = self.id
    ret
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!

  def index
    render :json => current_user.articles(params)
  end

  def update
    article = current_user.user_feed_articles.find(params[:id])
    article.update_attributes(safe_parameters)
    render :json => article
  end

  private
  def safe_parameters
    params.slice(:read, :keep_unread, :favorite)
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_filter :authenticate_user!

  def create
    user_feed = current_user.create_feed(params[:url])
    render :json => user_feed, :status => :created
  end

  def index
    render :json => current_user.user_feeds
  end

  def destroy
    user_feed = UserFeed.find(params[:id])
    user_feed.destroy
    render :json => {}, :status => :deleted
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'freader'
  #before_filter :authenticate_user!

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  respond_to :json
  def create
    response = Typhoeus::Request.post("https://verifier.login.persona.org/verify", {
            body: {audience: "http://freader.dev:80", assertion: params[:assertion]}
    })
    json = JSON.parse(response.body)
    @user = User.find_or_create_by_email(json['email'])
    sign_in @user
    render :json => @user.as_json
  end

  def destroy
    sign_out
    render :json => {}, :status => :no_content
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def authenticate_user!
    if current_user.nil?
      render :json => {}, :status => :unauthorized
      return false
    end
    true
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<h1>Listing feeds</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feeds.each do |feed| %>
  <tr>
    <td><%= feed.name %></td>
    <td><%= feed.url %></td>
    <td><%= link_to 'Show', feed %></td>
    <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
    <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @feed.name %>
</p>

<p>
  <b>Url:</b>
  <%= @feed.url %>
</p>


<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/home/index.html.erb
<div class="row-fluid">
  <div class="span3 sidebar-container">

    <!--/.well -->
  </div>
  <!--/span-->
  <div class="span9 main-container">

  </div><!--/span-->
</div><!--/row-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Freader: An open source feed reader.</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="An open source feed reader.">
    <meta name="author" content="justinkronz.com">

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= csrf_meta_tags %>

  </head>

  <body>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>

    </div><!--/.fluid-container-->

    <script src="https://login.persona.org/include.js"></script>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/freader.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Freader: An open source feed reader.</title>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="An open source feed reader.">
    <meta name="author" content="justinkronz.com">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>

  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Freader</a>
          <div class="nav-collapse collapse">
            <p id="user-status" class="navbar-text pull-right">

            </p>
            <ul class="nav">
              <li class="active"><a href="#" class="new-feed-link">Subscribe</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">More <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="/about">About</a></li>
                  <li><a href="/contact">Contact Me</a></li>
                  <li><a href="https://github.com/jkronz/autotunes" target="_blank">Check Out the Code</a></li>
                </ul>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <%= yield %>

      <hr>

    </div><!--/.fluid-container-->
    <script src="https://login.persona.org/include.js"></script>
    <%= javascript_include_tag "application" %>
  </body>
</html>